
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devop
            . ~/.devop/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
           
      - save_cache:
          paths:
            - ~/.devop
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . ~/.devop/bin/activate
               make lint 

      # run lints!
      #- run:
      #    name: run lint
      #    command: |
      #      . ~/.devop/bin/activate
      #      make lint

           
      # run lints!
      #- run:
      #    name: run lint
      #    command: |
      #      . ~/.devop/bin/activate
            

